Updating navbar-version-selector.html
etcd-io/website pull request #338
Opened 2021-05-28 00:31 UTC by nate-double-u

Now we always display the **Versions** menu but have made it **inactive** on pages where it doesn't apply.

fixes #304.

2021-05-28 00:34 UTC, nate-double-u commented
Deploy preview: https://deploy-preview-338--etcd.netlify.app/

2021-05-28 16:37 UTC, chalin requested changes
Thanks. Let's refactor this so that the dropdown html is always present, but the anchor has the added `disabled` class when not under `/docs`.

2021-05-28 17:10 UTC, nate-double-u commented
> Thanks. Let's refactor this so that the dropdown html is always present, but the anchor has the added `disabled` class when not under `/docs`.

I'm not sure how we can (if I'm understanding this request correctly).

If you mean something like
`<a class="nav-link dropdown-toggle {{ if ne .Section "docs" -}}disabled{{ end -}}" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">`
instead of the if else structure I've put in around the anchor/dropdown, then the template fails because the dropdown menu is looking for front-matter in the docs files that isn't present in the non-versioned pages.

I'm not sure what the dropdown html should be building on non versioned pages.

2021-05-28 17:21 UTC, chalin commented
> If you mean something like

Yes, almost: move the space inside the if: `<a class="nav-link dropdown-toggle{{ if ne .Section "docs" -}} disabled{{ end -}}"`

> the template fails

Darn. I wasn't expecting useful dropdown entires, but also wasn't expecting it to fail.

Ok then, put the `if eq .Section "docs"` around the _content_ of the `<div class="dropdown-menu" ...></div>`. Thanks.

2021-05-28 20:09 UTC, nate-double-u commented
> Ok then, put the `if eq .Section "docs"` around the _content_ of the `<div class="dropdown-menu" ...></div>`. Thanks.

The last commit does this -- but I don't like it as much as having a visually distinct _disabled_ versions selector.

2021-05-28 20:13 UTC, nate-double-u commented
> Ok then, put the `if eq .Section "docs"` around the _content_ of the `<div class="dropdown-menu" ...></div>`. Thanks.

The last (force pushed) commit does this -- but I don't like having an empty dropdown as much as having a visually distinct disabled versions selector.

2021-05-28 20:15 UTC, chalin requested changes
> I don't like having an empty dropdown as much as having a visually distinct _disabled_ versions selector.

Right, neither do I. We need both. So you can add the conditional inclusion of `disabled` (the way you had suggested earlier).

2021-05-28 20:24 UTC, nate-double-u commented
> ... We need both. So you can add the conditional inclusion of `disabled` (the way you had suggested earlier).

OK, added -- on Firefox disabling doesn't allow the dropdown to work, so we don't get an empty one on click. waiting for the build to check other browsers.

2021-05-28 20:25 UTC, nate-double-u commented
wait, i didn't do that quite correctly.
give me a moment :)

2021-05-28 20:29 UTC, nate-double-u commented
OK, the latest commit gives the `dropdown-menu` a chance to be empty if it's able to be shown at all.

2021-06-01 14:01 UTC, chalin commented
@nate-double-u - On Friday I was on the fence between accepting your original change and asking for extra rework in the context of this PR or later. I've changed my mind and, for now at least, I prefer the simplicity of your original change -- so I went ahead and stripped the extra commits to leave only the first one. While there is an opportunity to rework this fix to keep things a bit more DRY, that can come later.

2021-06-01 14:01 UTC, chalin approved these changes

2021-06-01 14:02 UTC, merged