fix: :bug: `etcdctl` for `snapshot status` is deprecated
etcd-io/website pull request #754
Opened 2023-12-04 07:26 UTC by mehdiMj-ir

The `etcdctl`  for `snapshot status` is deprecated and we should use `etcdutl` instead.
Signed-off-by: mehdiMj <mehdi.is@live.com>

2023-12-04 07:38 UTC, jmhbnz requested changes
Hey @mehdiMj-ir - Thanks for raising this fix!

I notice there are a few other instances in our supported documentation versions (`v3.5` and `v3.6`) that should also be updated:

```bash
 james  ~  Documents  website   main                                                                                                                                           20:35:16 
 ➜ grep -Ri "snapshot status" content/en/docs/v3.5/
content/en/docs/v3.5/op-guide/maintenance.md:$ etcdctl --write-out=table snapshot status backup.db

 james  ~  Documents  website   main                                                                                                                                           20:37:16 
 ➜ grep -Ri "snapshot status" content/en/docs/v3.6
content/en/docs/v3.6/tutorials/how-to-save-database.md:etcdctl --write-out=table --endpoints=$ENDPOINTS snapshot status my.db
content/en/docs/v3.6/op-guide/maintenance.md:$ etcdctl --write-out=table snapshot status backup.db
```

Can you please update those other references? 🙏🏻

2023-12-04 07:50 UTC, mehdiMj-ir commented
I pushed changes for `v3.5` and `v3.6`, thank you for considering my contribution.

2023-12-04 08:38 UTC, jmhbnz commented
Thanks @mehdiMj-ir - Can you please squash your commits?  This change should only be one commit, i.e:

```bash
git reset --soft HEAD~2
git commit -s -a -m "<message>"
git push --force
```

2023-12-04 09:52 UTC, ahrtr approved these changes

2023-12-04 15:39 UTC, spzala approved these changes
lgtm Thanks @mehdiMj-ir

2023-12-05 07:10 UTC, jmhbnz approved these changes
LGTM - Thanks @mehdiMj-ir 

cc @spzala for merge.

2023-12-05 13:35 UTC, merged