Described user roles
etcd-io/website pull request #852
Opened 2024-05-15 21:41 UTC by iiamabby

This PR pertains to issue #780  and also the umbrella issue #766 

Working on describing the 4 user roles defined in the initial analysis and implementation plan for the `etcd` doc updates. 

To note:  the initial implementation plan requests a link to each user workflow / tasks for each user group (#765). 

These are currently been developed and improved at the moment, for now they direct to the original `tutorials` page. 
 
Any suggestions / feedback welcome as always.

2024-05-16 09:39 UTC, jmhbnz reviewed
Hey @dwelsch-esi, @iiamabby - Having a look at the deploy preview for this change it feels confusing to have both a "Quickstart" and "Start here" section?

![image](https://github.com/etcd-io/website/assets/39425256/ab88d965-9a0b-47e4-b431-51129f56118e)

2024-05-16 20:34 UTC, iiamabby commented
Hey @jmhbnz possibly change to "Overview" instead of "Start here"?

2024-07-22 08:44 UTC, jmhbnz commented
> Hey @jmhbnz possibly change to "Overview" instead of "Start here"?

Hey @iiamabby I would suggest calling the page "Personas" or "User roles" as that is what the page seems to contain, thanks!

2024-08-26 23:01 UTC, jberkus commented
This has to wait on having some place for the roles to link to, no?

2024-08-27 21:28 UTC, dwelsch-esi commented
A suggestion: The titles ("Quickstart", "What's my role?", ...) should mirror the left-side menu and the page titles, but you can add short descriptions and headings to orient readers. Especially if this is the doc landing page, a bullet list might not give sufficient information to a new user seeing the docs for the first time.

Here's an example of how this might go:

# v3.6.0 docs

## Getting Started

Quickstart - Get a local instance of etcd running in less than five minutes

What's my role? - Decide what documentation you need based on your use cases

Demo - See what etcd can do

Install - Build from source or install pre-built binaries

Technical overview - learn about etcd

## User Guides

Tutorials - Instructions for specific scenarios

Metrics

Reporting bugs

Tuning

Discovery service protocol

## Reference

FAQ

Libraries and tools

Logging conventions

Golang modules

... and so on

2024-08-27 23:48 UTC, jberkus requested changes
Couple of text/format things.   Also, see questions/comments in discussion.

2024-08-27 23:48 UTC, jberkus commented on content/en/docs/v3.6/start_here.md
> +description: User roles and Persona's
```suggestion
description: User Roles and Personas
```

2024-08-27 23:48 UTC, jberkus commented on content/en/docs/v3.6/start_here.md
> +#### Use Cases
why the level 4 header here?  Shouldn't it be level 3?

2024-08-27 23:48 UTC, jberkus commented on content/en/docs/v3.6/start_here.md
> +
This needs to start off with an introduction, no?

2024-08-27 23:50 UTC, jberkus commented
Hey, I think this is going to work better if we create a feature branch for working on these docs.  What you have there, in terms of user roles and cases is great, but it needs a bunch of supporting text and reorganization before we can merge it into Main.

2025-01-05 19:54 UTC, closed without merging